# Generated by Django 5.2.11 on 2026-02-11 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("client_code", models.CharField(max_length=100, unique=True)),
                ("contact_person", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("street", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=20, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("gstin", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DepartmentContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("mobile", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClientUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_name", models.CharField(max_length=255)),
                ("unit_code", models.CharField(max_length=100)),
                (
                    "old_unit_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("print_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "billing_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("shipping_address", models.TextField(blank=True, null=True)),
                ("billing_address", models.TextField(blank=True, null=True)),
                (
                    "billing_from_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "billing_to_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "place_of_supply",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("place_of_supply_address", models.TextField(blank=True, null=True)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                ("pin_code", models.CharField(blank=True, max_length=20, null=True)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("gstin", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "state_office",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("field_area", models.CharField(blank=True, max_length=255, null=True)),
                ("attention", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("fax", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "work_order_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("work_order_date", models.DateField(blank=True, null=True)),
                ("work_start_date", models.DateField(blank=True, null=True)),
                ("work_completion_date", models.DateField(blank=True, null=True)),
                (
                    "agreement_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("agreement_date", models.DateField(blank=True, null=True)),
                ("agreement_exp_date", models.DateField(blank=True, null=True)),
                ("renewal_letter_date", models.DateField(blank=True, null=True)),
                ("no_of_employees", models.IntegerField(blank=True, null=True)),
                ("min_age", models.IntegerField(blank=True, null=True)),
                ("max_age", models.IntegerField(blank=True, null=True)),
                ("leave_opening", models.IntegerField(blank=True, null=True)),
                ("show_leave_on_pay_slip", models.BooleanField(default=False)),
                ("is_uniform_free", models.BooleanField(default=False)),
                (
                    "bonus_paid_in_month",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("pan_card_no", models.CharField(blank=True, max_length=50, null=True)),
                ("tan_no", models.CharField(blank=True, max_length=50, null=True)),
                ("tin_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "service_tax_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("pf_code", models.CharField(blank=True, max_length=50, null=True)),
                ("esic_code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "professional_tax_reg_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("roc", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "wages_revision",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("controller", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "salary_transferred_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gst_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "vendor_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("bill_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "bill_generate_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "print_format",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("bank", models.CharField(blank=True, max_length=255, null=True)),
                ("is_gst_applicable", models.BooleanField(default=True)),
                ("is_igst_applicable", models.BooleanField(default=False)),
                ("is_union_territory", models.BooleanField(default=False)),
                ("system_billing", models.BooleanField(default=False)),
                ("billing_in_decimal", models.BooleanField(default=False)),
                (
                    "contract_period_shown",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "nature_of_service",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rate_structure",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="clients.client",
                    ),
                ),
                (
                    "accounts_officer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounts_for",
                        to="clients.departmentcontact",
                    ),
                ),
                (
                    "operation_department",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations_for",
                        to="clients.departmentcontact",
                    ),
                ),
            ],
        ),
    ]
