# Generated by Django 5.2.11 on 2026-02-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="contractEndDate",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="contractStartDate",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
