# Generated by Django 5.2.11 on 2026-02-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_client_contractenddate_client_contractstartdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="contact_person",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
