# Generated by Django 5.2.11 on 2026-02-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employeeCode", models.CharField(max_length=250)),
                ("firstName", models.CharField(max_length=250)),
                ("middleName", models.CharField(blank=True, max_length=250, null=True)),
                ("lastName", models.CharField(max_length=250)),
                ("fatherName", models.CharField(blank=True, max_length=250, null=True)),
                ("motherName", models.CharField(blank=True, max_length=250, null=True)),
                ("dob", models.DateTimeField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Others", "Others"),
                        ]
                    ),
                ),
                ("maritalStatus", models.BooleanField(default=True)),
                ("spouseName", models.CharField(blank=True, max_length=250, null=True)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                ("phone", models.CharField(max_length=50)),
                ("mobileHome", models.CharField(blank=True, max_length=50, null=True)),
                ("position", models.CharField(blank=True, max_length=250, null=True)),
                ("department", models.CharField(blank=True, max_length=250, null=True)),
                ("hireDate", models.DateField()),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("height", models.CharField(blank=True, max_length=250, null=True)),
                ("weight", models.CharField(blank=True, max_length=250, null=True)),
                ("bloodGroup", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "identificationMark",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("shirtSize", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "trouserSize",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("shoeSize", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "presentStreet",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "presentState",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "presentCity",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "permanentStreet",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "permanentState",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "permanentCity",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "certifications",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "bankAccountNumber",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("branchName", models.CharField(blank=True, max_length=250, null=True)),
                ("ifscCode", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "aadharNumber",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("panNumber", models.CharField(blank=True, max_length=250, null=True)),
                ("uanNumber", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "esicIPNumber",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("pfNumbe", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "salaryDetails",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("documents", models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
